annotations:
  category: Streaming and messaging
  licenses: Memphis Business Source License 1.0
apiVersion: v2
name: memphis
description: Memphis.dev Official Helm chart
dependencies:
  - name: metadata
    condition: metadata.enabled
    version: "11.0.1"
home: https://github.com/memphisdev/memphis

keywords:
  - data streaming
  - message broker
  - memphis
  - producer
  - consumer
  - cluster
  - high availability
  
maintainers:
  - name: Memphis.dev
    url: https://k8s.memphis.dev/charts


type: application

sources:
  - https://github.com/memphisdev/memphis
  - https://www.memphis.dev
  
version: 1.0.3

appVersion: "1.0.3"

icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
