apiVersion: /v1
kind: Service
metadata:
  name: memphis-ui
  namespace: {{ include "nats.namespace" . }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.dashboard.port }}
      targetPort: 80
  selector:
    app: memphis-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memphis-ui
  namespace: {{ include "nats.namespace" . }}
  labels:
    app: memphis-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memphis-ui
  template:
    metadata:
      name: memphis-ui
      labels:
        app: memphis-ui
    spec:
      initContainers:
        - name: k8s-busybox-waits4broker
          image: busybox:1.28
          imagePullPolicy: Always
          command: ['sh', '-c', "until nslookup memphis-cluster.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for broker; sleep 2; done"]
      containers:
        - name: memphis-ui
          {{ if eq .Values.teston "ui" }}
          image: memphisos/memphis-ui-master-test:latest
          {{ else }}
          image: memphisos/memphis-ui:latest
          {{ end }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
