apiVersion: v1
kind: Secret
metadata:
  name: memphis-creds
  namespace: {{ include "memphis.namespace" . }}
type: Opaque
data:
  ROOT_PASSWORD: {{ if .Values.rootPwd }}{{ .Values.rootPwd | toString | b64enc | quote }}{{ else }}{{ randAlphaNum 20 | b64enc | quote }}{{ end }}
  CONNECTION_TOKEN: {{ if .Values.connectionToken }}{{ .Values.connectionToken | toString | b64enc | quote }}{{ else }}{{ randAlphaNum 20 | b64enc | quote }}{{ end }}
  JWT_SECRET: {{ randAlphaNum 128 | b64enc | quote }}
  REFRESH_JWT_SECRET: {{ randAlphaNum 128 | b64enc | quote }}
  JWT_SECRET_REST_GW: {{ randAlphaNum 128 | b64enc | quote }}
  REFRESH_JWT_SECRET_REST_GW: {{ randAlphaNum 128 | b64enc | quote }}
  AES_SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}
